### ISSUE TITLE
Web server Apache

### ISSUE THREAD

**Issue by vijaydsk** [esek/evote#24]
Hi
Am using Apache2 as the web server.
Can you please publish a document to install evote application?

**Comment by ginger51011** [comment]
Hi!

E-vote can be run on any web server configured for PHP. A quick DuckDuckGo search gives [this](https://www.raspberrypi.org/documentation/remote-access/web-server/apache.md) guide for Raspberry Pi, but this is pretty much the same for any Debian/Ubuntu machine.

I have updated the README with information about how to run locally :)
