### ISSUE TITLE
Codes not being accepted

### ISSUE THREAD

**Issue by paulg10me** [esek/evote#26]
Hi, I have evote set up in a test environment and it seems to have a problem accepting the codes that were issued for a vote.
I have not been able to get a successful vote submitted after several attempts.
The error says - "Your vote was not registered. This can depend on you entering one of the codes wrong, or because you already have voted"
Can anyone advise where I should look for a solution to this?
I have looked in the apache and mysql logs, but nothing jumps out as being wrong there.

**Comment by ginger51011** [comment]
Hi!

Are the temporary codes entered correctly?

**Comment by ginger51011** [comment]
Hi again,

I have been able to verify this bug locally. I will create a pull request shortly.
